//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesIndvPrjPkg
{
    [Serializable]
    public class ThrusterForcesMsg : Message
    {
        public const string k_RosMessageName = "interfaces_indv_prj_pkg/ThrusterForces";
        public override string RosMessageName => k_RosMessageName;

        public int[] thrusters;
        public float[] forces;

        public ThrusterForcesMsg()
        {
            this.thrusters = new int[16];
            this.forces = new float[16];
        }

        public ThrusterForcesMsg(int[] thrusters, float[] forces)
        {
            this.thrusters = thrusters;
            this.forces = forces;
        }

        public static ThrusterForcesMsg Deserialize(MessageDeserializer deserializer) => new ThrusterForcesMsg(deserializer);

        private ThrusterForcesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.thrusters, sizeof(int), 16);
            deserializer.Read(out this.forces, sizeof(float), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.thrusters);
            serializer.Write(this.forces);
        }

        public override string ToString()
        {
            return "ThrusterForcesMsg: " +
            "\nthrusters: " + System.String.Join(", ", thrusters.ToList()) +
            "\nforces: " + System.String.Join(", ", forces.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
